// APEX Shorts — vertical feed of 15-45 second driving lessons.
// Each short renders as a self-contained CSS scene + text overlays. Real video can
// replace the visual layer later by changing the `visual` field.

window.APEX_SHORTS = [
  {
    id: 's-pedestrian-popup', type: 'scenario', duration: 14,
    moduleNum: 1, moduleId: 'M1', tags: ['pedestrian', 'right-of-way'],
    title: 'The Pedestrian Pop-Up',
    hook: 'A van blocks the sidewalk. What\'s your move?',
    body: 'Cover the brake. Reduce speed. Scan for movement at edges (between vehicles, next to curbs). 23% of urban pedestrian collisions involve blocked sight lines.',
    rule: { tag: 'SMITH SYSTEM #2', text: 'Get the big picture. Treat anything that blocks your view as a hazard until proven otherwise.' },
    visual: 'scene-pedestrian',
    deeper: { label: 'Full lesson', href: 'lesson.html?id=1.3' },
  },
  {
    id: 's-3-second-rule', type: 'rule', duration: 18,
    moduleNum: 2, moduleId: 'M2', tags: ['following-distance'],
    title: 'The 3-second rule, in 3 seconds',
    hook: 'Pick a fixed point. Count one-thousand-1, one-thousand-2, one-thousand-3.',
    body: 'When the car ahead passes a sign, you should not reach that same sign for at least 3 seconds. Add 1 second per bad condition: rain, night, ice, towing.',
    rule: { tag: 'TX HANDBOOK', text: 'Following distance saves more crashes than any other defensive habit.' },
    visual: 'scene-following',
  },
  {
    id: 's-yield-pentagon', type: 'sign', duration: 12,
    moduleNum: 5, moduleId: 'M5', tags: ['signs'],
    title: 'The yellow pentagon ≠ yield',
    hook: '5-sided yellow sign. What is it?',
    body: 'School zone. Slow down to the posted school-zone limit when children are present. The classic yield sign is a downward-pointing triangle.',
    rule: { tag: 'SHAPE = MEANING', text: 'Octagon → STOP. Triangle → YIELD. Pentagon → SCHOOL. Diamond → WARNING.' },
    visual: 'scene-sign-pentagon',
  },
  {
    id: 's-blind-spot', type: 'habit', duration: 16,
    moduleNum: 2, moduleId: 'M2', tags: ['mirrors', 'lane-change'],
    title: 'Mirrors lie. Look over your shoulder.',
    hook: 'Side mirrors don\'t cover everything.',
    body: 'A whole sedan can hide in your blind spot. Before any lane change: signal, mirror, head-check over your shoulder, then move. SMOG: signal, mirror, over-the-shoulder, go.',
    rule: { tag: 'SMOG', text: 'Signal → Mirror → Over-the-shoulder → Go.' },
    visual: 'scene-blindspot',
    deeper: { label: 'Lane change scenario', href: 'lesson.html?id=2.3' },
  },
  {
    id: 's-implied-consent', type: 'fact', duration: 14,
    moduleNum: 7, moduleId: 'M7', tags: ['DUI', 'TX-law'],
    title: 'Refusing the breath test',
    hook: 'You don\'t have to take the breath test… or do you?',
    body: 'Texas implied-consent law: getting a driver license = consenting to a breath/blood test if a peace officer arrests you for DWI. Refuse and your license is automatically suspended for 180 days, even if you\'re later acquitted.',
    rule: { tag: 'TX TRANSP. CODE §724', text: 'License = consent. Refusal = automatic 180-day ALR suspension.' },
    visual: 'scene-fact',
  },
  {
    id: 's-stop-distance-physics', type: 'fact', duration: 18,
    moduleNum: 3, moduleId: 'M3', tags: ['speed', 'braking'],
    title: 'Stopping distance is not a feeling',
    hook: 'At 35 mph, how far do you need to stop?',
    body: 'On dry pavement: roughly 120 ft. That\'s 1.5 seconds of reaction + 50 ft of braking. Double the speed → quadruple the braking distance, not double.',
    rule: { tag: 'PHYSICS', text: 'KE = ½mv². Twice the speed = four times the energy you have to dump.' },
    visual: 'scene-physics',
    deeper: { label: 'Brake distance lesson', href: 'lesson.html?id=3.2' },
  },
  {
    id: 's-right-on-red', type: 'mistake', duration: 13,
    moduleNum: 4, moduleId: 'M4', tags: ['intersection', 'right-of-way'],
    title: 'Right turn on red ≠ free for all',
    hook: 'You CAN turn right on red. Most teens still do it wrong.',
    body: 'You must come to a COMPLETE stop first. Yield to all cross traffic AND pedestrians in the crosswalk. Look for "No Turn on Red" signs — they overrule the default.',
    rule: { tag: 'TX HANDBOOK', text: 'Stop · Yield · Then turn — only if no sign forbids it.' },
    visual: 'scene-rightonred',
  },
  {
    id: 's-hydroplane', type: 'rule', duration: 16,
    moduleNum: 6, moduleId: 'M6', tags: ['rain', 'control'],
    title: 'Hydroplaning: ease, don\'t stomp',
    hook: 'Steering wheel feels light. Tires lose grip in standing water.',
    body: 'Don\'t brake hard. Don\'t make sharp inputs. Ease off the gas, hold the wheel straight, let the tires re-engage. Hydroplaning starts as low as 35 mph in heavy rain.',
    rule: { tag: 'WET-WEATHER', text: 'No brake. No steer. Let the car settle.' },
    visual: 'scene-rain',
    deeper: { label: 'Wet-weather drill', href: 'drive.html?scenario=checkpoint' },
  },
  {
    id: 's-move-over', type: 'fact', duration: 12,
    moduleNum: 9, moduleId: 'M9', tags: ['TX-law'],
    title: 'TX Move Over law',
    hook: 'Police, fire, EMS, tow, TxDOT on the shoulder.',
    body: 'You must either move over one lane OR slow to 20 mph below the posted limit. Up to $500 fine. $2000 + jail if you cause an injury.',
    rule: { tag: 'TX TRANSP. CODE §545.157', text: 'Move over one lane or slow to limit-minus-20.' },
    visual: 'scene-moveover',
  },
  {
    id: 's-school-bus', type: 'rule', duration: 14,
    moduleNum: 5, moduleId: 'M5', tags: ['TX-law', 'school-bus'],
    title: 'Stopped school bus = full stop',
    hook: 'Red lights flashing. Stop arm out.',
    body: 'On a 2-lane road: BOTH directions stop. On a divided highway with a physical barrier between you and the bus: only the bus side stops. When in doubt, stop.',
    rule: { tag: 'TX TRANSP. CODE §545.066', text: 'Stop. Wait until the lights stop flashing AND the arm retracts.' },
    visual: 'scene-bus',
  },
  {
    id: 's-night-glare', type: 'habit', duration: 15,
    moduleNum: 6, moduleId: 'M6', tags: ['night'],
    title: 'Oncoming high beams blind you',
    hook: 'Don\'t stare into them.',
    body: 'Look down and to the right — track the white edge line until they pass. Your eyes need 6+ seconds to recover from glare. At 60 mph that\'s 528 feet of half-blind driving.',
    rule: { tag: 'NIGHT DRIVING', text: 'Eyes off oncoming. Eyes on the right edge line.' },
    visual: 'scene-night',
  },
  {
    id: 's-gdl-restrictions', type: 'fact', duration: 14,
    moduleNum: 9, moduleId: 'M9', tags: ['TX-law', 'GDL'],
    title: 'TX GDL: what you can\'t do at 16',
    hook: 'New license. New rules.',
    body: 'For the first 12 months OR until you turn 18 (whichever is sooner): no driving 12am–5am except for school/work/medical, no using a wireless device while driving (yes, even hands-free), and no more than one passenger under 21 who isn\'t family.',
    rule: { tag: 'TX TRANSP. CODE §545.424', text: 'Curfew · No phone · One non-family minor passenger.' },
    visual: 'scene-gdl',
  },
];

window.APEX_SHORTS_BY_ID = Object.fromEntries(window.APEX_SHORTS.map(s => [s.id, s]));
