// Rebuild curriculum_es.js from the re-translation batches (_es2_batch_A..E.json)
// and validate that every translated answer index matches the expanded English.
//
// Run: node scripts/merge_es.js

const fs = require('fs');
const path = require('path');
const SCRIPTS = path.join(__dirname, '..', 'frontend', 'scripts');

// 1. Load batches
const merged = {};
let batches = 0;
for (const b of ['A', 'B', 'C', 'D', 'E']) {
  const f = path.join(SCRIPTS, `_es2_batch_${b}.json`);
  if (!fs.existsSync(f)) { console.error(`MISSING batch: ${f}`); process.exit(1); }
  Object.assign(merged, JSON.parse(fs.readFileSync(f, 'utf8')));
  batches++;
}

// 2. Load English for parity
global.window = {};
require(path.join(SCRIPTS, 'curriculum.js'));
const EN = global.window.APEX_CURRICULUM;
const enById = {};
EN.allChapters.forEach(c => { enById[c.id] = c; });

// 3. Parity validation
const errors = [];
function checkArr(id, en, es, kind) {
  if (!en) return;
  if (!es) { errors.push(`${id}: ES missing ${kind}`); return; }
  if (en.length !== es.length) { errors.push(`${id}: ${kind} len EN ${en.length} != ES ${es.length}`); return; }
  en.forEach((q, i) => {
    if (q.correct !== es[i].correct) errors.push(`${id}: ${kind}[${i}] correct EN ${q.correct} != ES ${es[i].correct}`);
    if (q.options && es[i].options && q.options.length !== es[i].options.length) errors.push(`${id}: ${kind}[${i}] opt count differs`);
  });
}

const allIds = EN.allChapters.map(c => c.id);
const missing = allIds.filter(id => !merged[id]);
if (missing.length) errors.push(`ES missing chapters: ${missing.join(', ')}`);

allIds.forEach(id => {
  const en = enById[id], es = merged[id];
  if (!es) return;
  if (en.type === 'reading' || en.type === 'scenario') checkArr(id, en.quiz, es.quiz, 'quiz');
  if (en.type === 'checkpoint') checkArr(id, en.exam, es.exam, 'exam');
  if (en.type === 'scenario' && en.consequences) {
    const ec = en.consequences, sc = es.consequences || {};
    Object.keys(ec).forEach(l => {
      if (!sc[l]) errors.push(`${id}: ES consequences missing '${l}'`);
      else if (ec[l].good !== sc[l].good) errors.push(`${id}: consequences[${l}].good differs`);
    });
  }
  if (en.miniScenario) {
    if (!es.miniScenario) errors.push(`${id}: ES missing miniScenario`);
    else if (en.miniScenario.correct !== es.miniScenario.correct) errors.push(`${id}: miniScenario.correct EN ${en.miniScenario.correct} != ES ${es.miniScenario.correct}`);
  }
  if (en.worked && !es.worked) errors.push(`${id}: ES missing worked example`);
});

if (errors.length) {
  console.log(`--- ${errors.length} PARITY ERROR(S) ---`);
  errors.forEach(e => console.log('✗ ' + e));
  console.log('\nMerge ABORTED.');
  process.exit(1);
}

// 4. Write curriculum_es.js (ordered by id)
function sortIds(a, b) { const [am, ac] = a.split('.').map(Number); const [bm, bc] = b.split('.').map(Number); return am - bm || ac - bc; }
const ordered = {};
Object.keys(merged).sort(sortIds).forEach(id => ordered[id] = merged[id]);

const header = `// APEX — Spanish translations (all 12 modules, expanded content). Keyed by chapter id.
// Falls back to English when a key is missing. Mexican-Spanish-for-Texas voice.
// Generated by scripts/merge_es.js — answer indices verified against English.

window.APEX_CURRICULUM_ES = `;
const footer = `;

// Lookup helper — returns translated chapter if exists, else null.
window.APEX_CHAPTER_ES = function (id) { return window.APEX_CURRICULUM_ES[id] || null; };
`;
fs.writeFileSync(path.join(SCRIPTS, 'curriculum_es.js'), header + JSON.stringify(ordered, null, 2) + footer, 'utf8');
console.log(`PASS — rebuilt curriculum_es.js from ${batches} batches, ${Object.keys(ordered).length} chapters, all indices match English.`);
